# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
FLOAT_CFLAGS := -m32 -fno-builtin -c
FLOAT_CFILES := lib-common/FLOAT.c

$(FLOAT_OBJ): $(FLOAT_CFILES)
	$(call make_command, $(CC), $(FLOAT_CFLAGS), "complie FLOAT", $(FLOAT_CFILES))


