# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

# TODO: write a rule for generating $(FLOAT_OBJ)
CC := gcc
FLOAT_CFLAGS := -m32 -fno-builtin -c
FLOAT_CFILES := $$(shell find lib-common -name "*.c")
DIR := obj/lib-common

FLOAT.o: $(FLOAT_CFILES)
	$(CC) $(FLOAT_CFLAGS) $(FLOAT_CFILES) -o $(DIR)/FLOAT.o

